language: php
php:
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - JRE_HOME=/usr/lib/jvm/java-8-oracle
    - NEO_DIR=/tmp/neo
before_install:
  # install Oracle JDK8
  # Get dependencies (for adding repos)
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  # install oracle jdk 8
  - sudo apt-get install -y oracle-java8-installer
  - sudo update-alternatives --auto java
  - sudo update-alternatives --auto javac
  # install and launch neo4j
  - mkdir ${NEO_DIR}
  - pushd ${NEO_DIR}
  - wget http://dist.neo4j.org/neo4j-enterprise-3.0.1-unix.tar.gz > null
  - tar xzf neo4j-enterprise-3.0.1-unix.tar.gz --strip-components=1 > null
  - sed -i.bak '/\(dbms\.security\.auth_enabled=\).*/s/^#//g' ${NEO_DIR}/conf/neo4j.conf
  - ${NEO_DIR}/bin/neo4j start > null &
  - popd
  # remove xdebug
  - if [ $TRAVIS_PHP_VERSION == '7.2' ]; then phpenv config-rm xdebug.ini; fi;
install:
  - composer install
script:
  - vendor/bin/phpunit
