name: CI
on:
  - pull_request
  - push
jobs:
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
         - 7.3
         - 7.4
         - 8.0
    services:
      neo4j:
        image: neo4j
        options: >-
          --health-cmd "wget http://localhost:7474/browser -O -"
          --health-timeout 10s
          --health-retries 20
          --health-interval 10s
          --health-start-period 30s
        ports:
          - 7474:7474
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit
